# Generated by Django 4.1.7 on 2023-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_products_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.URLField(max_length=150),
        ),
    ]
