# Generated by Django 4.1.7 on 2023-02-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_products_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='site_maker',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='site_maker_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
